# Generated by Django 2.2.6 on 2019-10-10 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(default='', max_length=255)),
                ('types', models.CharField(choices=[('YARD', 'Yard'), ('WOODWORKING', 'Woodworking'), ('PLUMBING', 'Plumbing'), ('AUTO', 'Auto')], default='YARD', max_length=255)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted')),
            ],
        ),
    ]
