# Generated by Django 2.2.6 on 2019-10-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hey_neighbor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
