# Generated by Django 2.2.6 on 2019-10-11 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hey_neighbor', '0002_auto_20191010_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
