# Generated by Django 2.2.6 on 2019-10-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hey_neighbor', '0003_auto_20191011_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='boolean',
            new_name='availablility',
        ),
    ]
