# Generated by Django 2.2.6 on 2019-10-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hey_neighbor', '0004_auto_20191012_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='availablility',
            new_name='availability',
        ),
    ]
