# Generated by Django 2.2.6 on 2019-10-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hey_neighbor', '0006_tool_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='image',
        ),
    ]
